<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Heroic Features - Start Bootstrap Template</title>

  <!-- Bootstrap core CSS -->
  <link href="assets/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="assets/css/heroic-features.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Lobby</a>

      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <!-- Jumbotron Header -->
    <header class="jumbotron my-4">
      <h1 class="display-3">Welcome to the lobby!</h1>
      <p class="lead">
          You can use the form below to narrow your search!
      </p>
      <p class="row">
        <select class="form-control" id="brand-select">
            <option selected value="null">Select a Brand</option>
            <?php foreach ($brands as $brand) : ?>
                <option value="<?php echo $brand[0] ?>"><?php echo $brand[1] ?></option>
            <?php endforeach; ?>
        </select>
      </p>
      <p class="row">
        <select class="form-control" id="country-select">
            <option selected value="null">Select a country</option>
        <?php foreach ($countries as $country) : ?>
            <option value="<?php echo $country ?>"><?php echo $country ?></option>
        <?php endforeach; ?>
        </select>
      </p>
      <p class="row">
        <select class="form-control" id="category-select">
            <option selected value="null">Select a category</option>
        <?php foreach ($categories as $category) : ?>
            <option value="<?php echo $category[0] ?>"><?php echo $category[1] ?></option>
        <?php endforeach; ?>
        </select>
      </p>
      <p class="row">
          <button type="button" class="btn btn-primary" id="game-search-btn">Search</button>
      </p>
    </header>

    <!-- Page Features -->
    <div class="row text-center" id="games-container"></div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-2 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="assets/jquery/jquery.min.js"></script>
  <script src="assets/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="assets/lobby/application.php"></script>

</body>

</html>
