version: "3"

services:
  apiwebserver:
    container_name: api-server
    build:
      context: ./
    working_dir: /var/www/html/api
    ports:
      - "8088:80"
    volumes:
      - ../:/var/www/html/api
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./config/api.conf:/etc/apache2/sites-enabled/default.conf
      - ./logs/apache2:/var/log/apache2
    environment:
      - APPLICATION_ENV=development
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: api-db
    volumes:
      - my-db:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d:ro
    restart: always
    ports:
      - 4306:3306
    environment:
      MYSQL_DATABASE: 'cms'
      MYSQL_ROOT_PASSWORD: 'rootpass'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'dbpass'

volumes:
  my-db: